### ISSUE TITLE
Aspect Description will not save

### ISSUE THREAD

**Issue by jdgcoop** [Sk1mble/fate-core-official#15]
I changed one of the two Free Aspects in Fate Condensed to a "Powers" aspect, but the Aspect description edits will not save, it keeps the default aspect description no matter what I do.  For a work-around, it is possible to delete the original aspect entirely, and then create a new one, and the descriptions save fine in the created Aspect, but although a user can change the name of a pre-created / default aspect, I cannot find any way to change its description.

**Comment by Sk1mble** [comment]
Thanks for bringing this to my attention.

I think what you did was click and drag to select the text you wanted to replace, yes?

What's happening here, is that although it looks like a standard text box, the aspect description field is actually two paired text boxes. It displays a fully rendered HTML string using a sanitizer function to make sure that there's no iffy code, but when you click on it this box is hidden and the edit box is revealed. This two-step shuffle was necessary to enable Foundry inner links (e.g. @actor links etc.) to be properly converted for display without being overwritten every time.

When you click in the displayed rich text box, it hides this box and gives focus to the edit box, which is where changes are made.

What I didn't realise was that a dragstart event (e.g. when you select text) does NOT trigger a click event. Therefore, when you drag to select the existing aspect description, it never switches out to the edit box and when you make changes you're editing the DISPLAY version of the description and not the raw text.

I need to ponder whether to add dragstart methods to prevent this from happening, and possibly do something clever to set the cursor position in the edit box to the same place where you clicked on the display box--at the moment the cursor jumps to the start of the edit box because of the change in focused element behind the scenes.

That's going to be a fairly lengthy process as I investigate the best option and deploy it throughout the code base (there's a LOT of these fields - essentially any time it's displaying rich text) but I wanted to let you know what the problem was and give you a solution.

Instead of dragging directly on the description to select the text and then editing it, all you have to do is click on the box first, THEN drag to select and delete the existing contents before replacing it with the new aspect description.

**Comment by Sk1mble** [comment]
Okay, looking into it a bit further, what's happened is you've dragged outside the text box, when you selected the text, meaning that the click event didn't fire. I'm looking into solutions for this, but in the meantime you can click on the box and select all with Ctrl-A, or click in the box and then select, or you can carefully ensure your cursor is inside the box when you release the mouse button.

**Comment by jdgcoop** [comment]
Hi Sk1mble:

Not sure I followed your whole explanation, but just for clarity sake, I
wasn't dragging and dropping anything, not from a user perspective.

My issue happened more like this.
1. Setup standard Aspects via overwrite button in settings
2. Open Aspect editing in settings
3. Type new name of Aspect over old
4. Type new description over old
5. Save

Only the name is different, the description is exactly as it was before I
started typing.  Very odd.  I had to do it 4 or 5 times to convince myself
it was really happening and I wasn't making some sort of a mistake.

I don't really know how to explain it.  And, after doing it a bunch of
times, I just deleted the standard Aspect and created a new one.  That
works.  But editing the standard never did for me.

-JC

- - - -

Nasrudin sat in a temple with his feet on the altar.

The keeper of the temple entered the room and became quite distressed.

“Mulla Nasrudin,” he said.  “You must remove your feet from the altar, for
it is holy.”

Nasrudin replied, “Where would you have me put my feet then…?”

Sufi Parable
<https://www.azquotes.com/author/2054-Elizabeth_Barrett_Browning>

Rev. John D. Cooper, BCC | Pronouns: He, Him, His
Email: ***@***.*** | Phone: 801-558-7679
Website: http://www.woundedwalker.com

**Comment by Sk1mble** [comment]
I think you drag selected all of the text in the box. That's how I was able
to replicate the issue.

Try clicking first, then selecting, and see if the problem persists. ;)

**Comment by jdgcoop** [comment]
I think you're right and it's appropriate to close the issue.  Unfortunate
that the UI behavior is clunky, but sounds like a library you're using.
The floating toolbar is a bit odd as well.  Looks slick, but it's state
handling seems odd, I've had it float over the table-top after I closed
every place I was using it and had to reload Foundry to get it to go away.

I'll try to make sure the editing area is active and the tool bar engaged
before making changes, maybe that will help.



- - - -

Nasrudin sat in a temple with his feet on the altar.

The keeper of the temple entered the room and became quite distressed.

“Mulla Nasrudin,” he said.  “You must remove your feet from the altar, for
it is holy.”

Nasrudin replied, “Where would you have me put my feet then…?”

Sufi Parable
<https://www.azquotes.com/author/2054-Elizabeth_Barrett_Browning>

Rev. John D. Cooper, BCC | Pronouns: He, Him, His
Email: ***@***.*** | Phone: 801-558-7679
Website: http://www.woundedwalker.com
