### ISSUE TITLE
Wrong Foundry version (10.260 vs current 9.269) - can't update

### ISSUE THREAD

**Issue by techogre** [Sk1mble/fate-core-official#30]
When I try to update the fate-core-official modules I get an error:

![update error screenshot](https://user-images.githubusercontent.com/10929680/164453445-7f1195ac-07c6-42f3-b8d4-0c7cb25f92ad.png)

**Comment by Sk1mble** [comment]
Hi, I am unsure why this is happening, because the master repository that's pointed to on the Foundry website doesn't point to the later versions (which I've been developing in prototype for 10.260.

In any case, if you have version 4.3.25 you already have the latest version compatible with version 9. If you have an earlier version than that and cannot update, you can try to uninstall and reinstall the system, or install manually from:

https://raw.githubusercontent.com/Sk1mble/fate-core-official/v4.3.25/system.json
