### ISSUE TITLE
[Feature Request] Synchronise Conflicts and the Combat Tracker

### ISSUE THREAD

**Issue by mrianmerry** [Sk1mble/fate-core-official#45]
Would it be possible to synchronise the Combat Tracker in Foundry with the Conflict menu in the Fate Utilities?

Our table uses Maestro to set hype tracks for characters, and it would be great if we could continue to use the popcorn initiative from the Conflict menu whilst enjoying Combat Tracker's auto-play for the hype tracks.

Thanks in advance.

**Comment by Sk1mble** [comment]
This is enabled to an extent in 4.4.41, but only to use the built in combat sounds in Foundry. It's very difficult to integrate the conflict tracker from Foundry with popcorn initiative because the concept of an initiative score and stepping through it is meaningless.

On top of this, I don't know exactly how Maestro does what it does.

There is now code in Fate Core Official to override the core Foundry way of playing sounds when the initiative skill is set to "None" as follows:

```
    // Override the Foundry combat sound process to account for popcorn initiative, if we're using that.
    let init_skill = game.settings.get("fate-core-official","init_skill");
    if (init_skill == "None") {
        Combat.prototype._playCombatSound = function (announcement) {
            if (announcement == "nextUp") return;
            if (announcement == "yourTurn") return;
            if (announcement == "yourAction") announcement = "yourTurn";

            if ( !CONST.COMBAT_ANNOUNCEMENTS.includes(announcement) ) {
                throw new Error(`"${announcement}" is not a valid Combat announcement type`);
              }
              const theme = CONFIG.Combat.sounds[game.settings.get("core", "combatTheme")];
              console.log(theme);
              if ( !theme || theme === "none" ) return;
              const sounds = theme[announcement];
              if ( !sounds ) return;
              const src = sounds[Math.floor(Math.random() * sounds.length)];
              const volume = game.settings.get("core", "globalInterfaceVolume");
              game.audio.play(src, {volume});
        }
    }
```
If Maestro overrides the 'Your turn' and 'begin combat' sounds, then this should work as you want it to, otherwise you may need to do some more work with a world module.

Thanks,

Richard

**Comment by Sk1mble** [comment]
Yeah, this won't work with Maestro, because Maestro hooks into updates to the combat and plays the hype track for the current combatant from a playlist.  This relies on knowing who the current combatant is, which is a function of initiative and the current turn.

**Comment by Sk1mble** [comment]
Okay, I have figured out a way to do this that definitely works with Maestro, and pushed it as v4.4.42.

# 4.4.42
* Found a way to make the Popcorn tracker play better with the Foundry standard initiative system, so that now Foundry and FCO agree on whose turn it is. This enables modules like Maestro to correctly cue off of changes of turn to play hype tracks etc.
