### ISSUE TITLE
Actors - Permissions

### ISSUE THREAD

**Issue by jasharen** [Sk1mble/fate-core-official#5]
Not sure where to send requests, so thought I would try here. Please close if you are not considering requests.

Is it possible to limit visibility of actor sheets based on permissions.

For example:
Limited - Only grants access to Name, Description and portrait/image?

This would allow for easy tracking of npcs for players. Right now, if I give limited access players can essentially see everything about the actor.

Thanks and awesome work!

**Comment by Sk1mble** [comment]
Fate doesn't really do partial information, generally, so this has not been a priority for me. However, due to demand there are a few options available to you. 

1) Create two versions of each secret character, public and private
2) Use the binoculars tool to show specific parts of an NPC to one or more players when they want to see it
3) Edit a copy of the sheet and use this setting to control what can be seen in Limited view:

![image](https://user-images.githubusercontent.com/1439478/120906595-b3238700-c652-11eb-89a5-bda7d697fc71.png)

You can hack this sheet as much as you like.
