### ISSUE TITLE
Situation Aspects - Feature Suggestions

### ISSUE THREAD

**Issue by buttonpushertv** [Sk1mble/fate-core-official#9]
I love the premise of the Situation Aspect tool. I do have some thoughts about ways to improve some aspects(ha!) of it, though, after working with it some.

Some of the issues become apparent when you see what I'm doing with it:
![Inkedscreenshot 1625365791_LI](https://user-images.githubusercontent.com/24526709/124371347-f91e3b80-dc4e-11eb-85e8-35d5a082f3ee.jpg)

Purple Arrow - With no value in the Label Fill and Border Colors, I was hoping that they would then become transparent. Having the ability to make them transparent could be useful when adding them to a running document like this example in WWN. Can there be an option to make them completely transparent?

Green Box - Could there be a check box or option to put the Aspect on the scene without a "(0 free invokes)" text? I understand the intent, but that flexibility would help for use of things like these "Investigation Notes" where I'd like to use the tool, but I don't need to track invokes on each item. 

Blue Box - Enable or toggle Draw Tool Select - it would be great if, after you put the Aspect on the Scene, it automatically switch the current tool over to the Draw Select Tool or if there were another button here that could switch to that tool (instead of having to go all the way over to the left side toolbar). {I would normally be running with a module that  would allow me to switch to that tool via the keyboard, but running without it as I develop WWN, shows me how awkward & tedious it would be for someone who wanted to just move the Aspect slight after placing it.}

Thank you for all the great work you do!

**Comment by Sk1mble** [comment]
I'll look into automatically selecting the drawing layer after creating an
aspect, but I suspect that would also be annoying for some people as it
would be an unexpected behaviour. This is essentially an annoying
limitation of Foundry that anyone who's bothered by will probably have
installed a module to address.

I'm not changing the presentation of free invokes for situation aspects. If
you don't want it to show free invokes, is it actually situation aspects
you're tracking? Maybe you need to write a macro that adds new clues to the
running list rather than using the situation aspect tool. That would also
address your desire for transparency, and would allow it to be a single
aligned text box rather than multiple.

**Comment by Sk1mble** [comment]
v4.1.11 adds settings for border and fill transparency and automatically selects the drawing layer when you add a new aspect label.
